server:
  servlet-path: /
  error:
    whitelabel:
      enabled: false
  port: 7001
  tomcat:
    uri-encoding: UTF-8

spring:
  mvc:
    servlet:
      load-on-startup: 1
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
  thymeleaf:
    cache: false
    profiles:
      active: dev
  application:
    name: Teach-ioc1                          #微服务的名字

feign:
  hystrix:
    enabled: true   #开启熔断器功能


eureka:
  client:
    #register-with-eureka: false
    service-url:
      defaultZone: http://eureka9001.com:9001/eureka/
  instance:
    instance-id: teach-ioc1:7001  is  already 	#自定义服务名称信息
    prefer-ip-address: true                                   #访问路径可以显示IP地址

info:
  app.name: Teach-ioc1:7001
  company.name: www.lzj.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}
